sudo: true
dist: xenial 
services:
  - docker
language: python 
python:
  - "3.4"

before_install:
  - pip3 install cwltool
  - docker build -t base_counter .

script:
  # Both of these same tests, in Docker
  # Functional tests
  - docker run --entrypoint /base_counter/.travis/unit-test.sh base_counter
  # Unit tests
  - docker run --entrypoint /base_counter/functional_tests/base_counter-test.sh base_counter -p base_counter -d /base_counter/functional_tests/test_data -v

  # CWL definition test
  - cwltool base_counter.cwl --fasta_file functional_tests/test_data/two_sequence.fasta
